---
- name: "Install Docker (1/2)"
  apt:
    name: docker.io
    state: present

- name: "Install Docker Daemon Config (2/3)"
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: "Start and enable Docker (3/3)"
  systemd:
    state: started
    daemon_reload: yes
    name: docker
    enabled: yes