---
users:
  - jgavinray

kubernetes_version: v1.20.0
kubeadm_version: 1.20.0

kubernetes_loadbalanced_api_dns: k8s-api01.domain.local
kubernetes_cluster_label: jgavinray.cloud

# Kubernetes Kubeadm Cluster Configuration
kubeadm_config_options:
    apiVersion: kubeadm.k8s.io/v1beta1
    kind: ClusterConfiguration
    kubernetesVersion: "{{ kubernetes_version }}"
    controlPlaneEndpoint: "192.168.0.25"
    networking:
        podSubnet: 10.244.0.0/16
    clusterName: "{{ kubernetes_cluster_label }}"
